# Generated by Django 3.2.6 on 2021-08-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='descr',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='hashtag',
            new_name='hashtags',
        ),
    ]
