# Generated by Django 3.2.6 on 2021-09-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210906_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='datatime',
        ),
        migrations.AddField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
